[package]
name = "pew"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.21"
colored = "2.1.0"
notify = "7.0.0"
serde_json = "1.0.133"
toml = "0.8.19"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0.93"
regex = "1.11.1"
glob = "0.3.1"
